"""Mapping pays -> zone geographique (approximation simple, non exhaustive)."""

_COUNTRY_TO_REGION = {
    "United States": "Amerique du Nord",
    "Canada": "Amerique du Nord",
    "Mexico": "Amerique du Nord",
    "France": "Europe",
    "Germany": "Europe",
    "United Kingdom": "Europe",
    "Ireland": "Europe",
    "Luxembourg": "Europe",
    "Netherlands": "Europe",
    "Switzerland": "Europe",
    "Spain": "Europe",
    "Italy": "Europe",
    "Belgium": "Europe",
    "Sweden": "Europe",
    "Norway": "Europe",
    "Denmark": "Europe",
    "Finland": "Europe",
    "Austria": "Europe",
    "Portugal": "Europe",
    "Poland": "Europe",
    "Czech Republic": "Europe",
    "Greece": "Europe",
    "Japan": "Asie",
    "China": "Asie",
    "Hong Kong": "Asie",
    "South Korea": "Asie",
    "Taiwan": "Asie",
    "India": "Asie",
    "Singapore": "Asie",
    "Indonesia": "Asie",
    "Thailand": "Asie",
    "Malaysia": "Asie",
    "Vietnam": "Asie",
    "Israel": "Moyen-Orient",
    "United Arab Emirates": "Moyen-Orient",
    "Saudi Arabia": "Moyen-Orient",
    "Australia": "Oceanie",
    "New Zealand": "Oceanie",
    "Brazil": "Amerique du Sud",
    "Argentina": "Amerique du Sud",
    "Chile": "Amerique du Sud",
    "Colombia": "Amerique du Sud",
    "South Africa": "Afrique",
    "Egypt": "Afrique",
    "Nigeria": "Afrique",
    "Cayman Islands": "Offshore",
    "Bermuda": "Offshore",
    "British Virgin Islands": "Offshore",
    "Jersey": "Offshore",
    "Guernsey": "Offshore",
}


def country_to_region(country: str | None) -> str | None:
    if not country:
        return None
    return _COUNTRY_TO_REGION.get(country, "Autre")
